"""
Asset Bundle Exporter for AI Content Factory SaaS.
Creates high-speed ZIP archives of complete video packages for creators.
"""

import os
import io
import json
import zipfile
from pathlib import Path
from typing import Dict, Any, Optional
from utils.helpers import logger


def create_asset_bundle_zip(production_data: Dict[str, Any]) -> io.BytesIO:
    """
    Packages video, thumbnail, audio, SRT subtitles, and SEO metadata into a ZIP bundle.
    Returns in-memory BytesIO buffer ready for st.download_button.
    """
    buffer = io.BytesIO()
    
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # 1. Add Video
        v_path = production_data.get("video_path")
        if v_path and os.path.exists(v_path):
            zf.write(v_path, arcname=f"media/{os.path.basename(v_path)}")
        
        # 2. Add Thumbnail(s)
        t_path = production_data.get("thumbnail_path")
        if t_path and os.path.exists(t_path):
            zf.write(t_path, arcname=f"thumbnails/{os.path.basename(t_path)}")
        
        # 3. Add Audio
        a_path = production_data.get("audio_path")
        if a_path and os.path.exists(a_path):
            zf.write(a_path, arcname=f"audio/{os.path.basename(a_path)}")
        
        # 4. Add Subtitles (SRT)
        s_path = production_data.get("srt_path")
        if s_path and os.path.exists(s_path):
            zf.write(s_path, arcname=f"subtitles/{os.path.basename(s_path)}")
        
        # 5. Add SEO & Metadata JSON
        metadata = {
            "title": production_data.get("title", "AI Content Package"),
            "niche": production_data.get("niche", "general"),
            "content_type": production_data.get("content_type", "video"),
            "orientation": production_data.get("orientation", "landscape"),
            "resolution": production_data.get("resolution", "1080p"),
            "elapsed_seconds": production_data.get("elapsed_seconds", 0),
            "seo": production_data.get("seo", {}),
            "script": production_data.get("script", {})
        }
        zf.writestr("metadata/production_info.json", json.dumps(metadata, indent=2))
        
        # 6. Add Human-Readable Readme / Copy-Paste text
        readme_content = f"""# {metadata['title']}
AI Content Factory Pro Production Bundle

## 📌 Best Video Title:
{metadata.get('seo', {}).get('best_title', metadata['title'])}

## 📝 YouTube / TikTok Description:
{metadata.get('seo', {}).get('description', '')}

## 🏷️ Tags:
{', '.join(metadata.get('seo', {}).get('tags', []))}

## #️⃣ Hashtags:
{' '.join(metadata.get('seo', {}).get('hashtags', []))}

---
Generated by AI Content Factory Pro (100% Free Autonomous Media Engine).
"""
        zf.writestr("PUBLISH_READY_COPY_PASTE.txt", readme_content)

    buffer.seek(0)
    return buffer
